In [59]:
import numpy as np
x = np.array([1,2,3,4,5]).reshape(1, 5) #square meters
n_datapoints = x.shape[1]
d = np.array([100,150,160,160,200]).reshape(1, 5)
w = np.random.sample((n_datapoints, n_datapoints))
mu = 0.1
print "w", w.shape, w
print "x", x.shape, x
print "d", d.shape, d

w (5, 5) [[ 0.54842384  0.56282506  0.70586371  0.68381839  0.55682882]
 [ 0.43224348  0.00208626  0.4547223   0.58949796  0.54524531]
 [ 0.61198126  0.28899437  0.84317888  0.42983833  0.34261073]
 [ 0.03552983  0.94391907  0.30456204  0.33470781  0.99325834]
 [ 0.21100251  0.38372532  0.8690576   0.07291716  0.90069032]]
x (1, 5) [[1 2 3 4 5]]
d (1, 5) [[100 150 160 160 200]]


y = f(x,w) = w'x

error:

e = d - w'x

d = datapoint

In [60]:
y = w.transpose() * x
y

array([[  5.48423840e-01,   8.64486953e-01,   1.83594377e+00,
          1.42119327e-01,   1.05501257e+00],
       [  5.62825057e-01,   4.17251460e-03,   8.66983124e-01,
          3.77567627e+00,   1.91862661e+00],
       [  7.05863711e-01,   9.09444594e-01,   2.52953664e+00,
          1.21824815e+00,   4.34528800e+00],
       [  6.83818389e-01,   1.17899592e+00,   1.28951498e+00,
          1.33883122e+00,   3.64585817e-01],
       [  5.56828821e-01,   1.09049062e+00,   1.02783218e+00,
          3.97303337e+00,   4.50345159e+00]])

In [48]:
e = d - y
e

array([[  99.27256215,  148.5451243 ,  157.81768645,  157.09024861,
         196.36281076]])

In [49]:
w = w + mu * e
w

array([[ 10.65469406,  15.58195028,  16.50920649,  16.43646271,
         20.36371892]])

In [50]:
y = w.transpose() * x
y

array([[  10.65469406,   21.30938813,   31.96408219,   42.61877625,
          53.27347032],
       [  15.58195028,   31.16390056,   46.74585084,   62.32780112,
          77.90975139],
       [  16.50920649,   33.01841299,   49.52761948,   66.03682598,
          82.54603247],
       [  16.43646271,   32.87292542,   49.30938813,   65.74585084,
          82.18231355],
       [  20.36371892,   40.72743785,   61.09115677,   81.4548757 ,
         101.81859462]])